version: "3.5"

services:
  JS:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=JS
    image: postgres:14.3-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
